# 데이터 획득 및 설정

In [1]:
import sqlalchemy as db
import datetime
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
import os

In [2]:
engine = create_engine('mysql://sbe03253:jin94099@database-2.clmg3ftdxi2a.ap-northeast-2.rds.amazonaws.com/MJTradierDB')
conn = engine.connect()

In [3]:
metadata = db.MetaData()
table = db.Table('scaleDatasDict', metadata, autoload=True, autoload_with=engine)

In [4]:
br = pd.read_sql_table('buyReports', conn)

In [5]:
# Filtering
br = br[( br['isAllBuyed'] == 1) & ( br['isAllSelled'] == 1) & (br['nBuyVolume'] > 0)]

In [6]:
feature_names =  [   
        'nBuyStrategyIdx',
        'nRqTime' , 
        'fStartGap' ,
        'fPowerWithOutGap' , 
        'fPower' , 
        'fPlusCnt07' , 
        'fMinusCnt07' , 
        'fPlusCnt09' , 
        'fMinusCnt09' ,
        'fPowerJar' , 
        'fOnlyDownPowerJar' , 
        'fOnlyUpPowerJar' , 
        'nTradeCnt' , 
        'nChegyulCnt' , 
        'nHogaCnt' , 
        'nNoMoveCnt' , 
        'nFewSpeedCnt' ,
        'nMissCnt' , 
        'lTotalTradeVolume' , 
        'lTotalBuyVolume' , 
        'lTotalSellVolume' ,
        'nAccumUpDownCount' ,
        'fAccumUpPower' , 
        'fAccumDownPower' ,
        'lTotalTradePrice' , 
        'lTotalBuyPrice' , 
        'lTotalSellPrice' , 
        'lMarketCap' , 
        'nAccumCountRanking' , 
        'nMarketCapRanking' , 
        'nPowerRanking' , 
        'nTotalBuyPriceRanking' , 
        'nTotalBuyVolumeRanking' ,
        'nTotalTradePriceRanking' ,
        'nTotalTradeVolumeRanking' ,
        'nTotalRank' , 
        'nMinuteTotalRank' , 
        'nMinuteTradePriceRanking' ,
        'nMinuteTradeVolumeRanking' , 
        'nMinuteBuyPriceRanking' , 
        'nMinuteBuyVolumeRanking' ,
        'nMinutePowerRanking' , 
        'nMinuteCountRanking' ,
        'nMinuteUpDownRanking' ,
        'nFakeBuyCnt' , 
        'nFakeAssistantCnt' ,
        'nFakeResistCnt' , 
        'nPriceUpCnt' , 
        'nPriceDownCnt' ,
        'nTotalFakeCnt' ,
        'nTotalFakeMinuteCnt' ,
        'nUpCandleCnt' , 
        'nDownCandleCnt' ,
        'nUpTailCnt' , 
        'nDownTailCnt' ,
        'nShootingCnt' ,
        'nCandleTwoOverRealCnt' ,
        'nCandleTwoOverRealNoLeafCnt' , 
        'fSpeedCur' , 
        'fHogaSpeedCur' ,
        'fTradeCur' , 
        'fPureTradeCur' , 
        'fPureBuyCur' , 
        'fHogaRatioCur' ,  
        'fSharePerHoga' , 
        'fSharePerTrade' ,
        'fHogaPerTrade' , 
        'fTradePerPure' , 
        'fMaDownFsVal' , 
        'fMa20mVal' , 
        'fMa1hVal' ,
        'fMa2hVal' ,
        'fMaxMaDownFsVal' ,
        'fMaxMa20mVal' ,
        'fMaxMa1hVal' ,
        'fMaxMa2hVal' ,
        'nMaxMaDownFsTime' ,
        'nMaxMa20mTime' ,
        'nMaxMa1hTime' ,
        'nMaxMa2hTime' ,
        'nDownCntMa20m' ,
        'nDownCntMa1h' ,
        'nDownCntMa2h' ,
        'nUpCntMa20m' ,
        'nUpCntMa1h' ,
        'nUpCntMa2h' ,
        'fMSlope' ,
        'fISlope' ,
        'fTSlope' ,
        'fHSlope' ,
        'fRSlope' ,
        'fDSlope' ,
        'fMAngle' ,
        'fIAngle' ,
        'fTAngle' ,
        'fHAngle' ,
        'fRAngle' ,
        'fDAngle' ,
        'nCrushCnt' ,
        'nCrushUpCnt' ,
        'nCrushDownCnt' ,
        'nCrushSpecialDownCnt' 
]

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.preprocessing import Normalizer

X = br[
   feature_names
]
MINMAX = 'MinMax'
ROBUST = 'Robust'
STANDARD = 'Standard'

scale_method = MINMAX
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

# transformer = Normalizer().fit(X)  
# X = transformer.transform(X)

print(type(X))
print(X)
#X = X.to_numpy()

<class 'numpy.ndarray'>
[[0.20338983 0.22074577 0.49956934 ... 0.         0.         0.        ]
 [0.10169492 0.97527707 0.4861169  ... 0.         0.         0.        ]
 [0.11016949 0.97694503 0.4861169  ... 0.         0.         0.        ]
 ...
 [0.61016949 0.37631121 0.50363788 ... 0.2        0.5        0.        ]
 [0.61016949 0.6635902  0.50363788 ... 0.3        0.         0.        ]
 [0.74576271 0.21331406 0.50363788 ... 0.1        0.5        0.        ]]


In [8]:
# y_continuos = br[ ['fProfit'] ]
# y_categorical = (br['fProfit'].apply(lambda x: 1 if x >= 0.01 else 0)).to_frame() # categorical
# y_categorical = b
type(X)

numpy.ndarray

In [9]:
crit = 0.015
br.loc[br['fProfit'] >= crit, 'isProfit'] = 1
br.loc[br['fProfit'] < crit, 'isProfit'] = 0
# y = pd.get_dummies( br['isProfit'] )
y = br['isProfit']
y = y.to_numpy()

# y = br['fProfit'] * 100
# y

In [10]:
# br.loc[br['fMaxPowerAfterBuyWhile10'] >= 0.035, 'isGood'] = 1
# br.loc[br['fMaxPowerAfterBuyWhile10'] < 0.035, 'isGood'] = 0
# # y = pd.get_dummies( br['isGood'] )
# y = br['isGood']
# y = y.to_numpy()

In [11]:
br['isProfit'].unique()

array([0., 1.])

In [12]:
# br['isGood'].unique()

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=16)

In [14]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
y_train

(47700, 102)
(47700,)
(15900, 102)
(15900,)


array([1., 0., 0., ..., 0., 0., 1.])

In [15]:
X[1]

array([1.01694915e-001, 9.75277067e-001, 4.86116900e-001, 5.17588278e-001,
       5.47480426e-001, 1.76134552e-002, 3.27411217e-004, 1.16248710e-002,
       1.03920088e-003, 4.16377494e-001, 1.00000000e+000, 1.06715072e-001,
       0.00000000e+000, 1.39011753e-003, 1.08462392e-002, 4.18604651e-001,
       4.45121951e-001, 4.02684564e-001, 1.07090230e-003, 1.10389458e-003,
       1.03115848e-003, 1.07991361e-003, 1.62131879e-003, 1.60933347e-003,
       4.67514242e-004, 3.98067957e-004, 5.75142764e-004, 3.86424818e-004,
       5.73862050e-001, 3.65363128e-001, 5.53611111e-001, 1.51279199e-001,
       1.85833333e-001, 4.10470621e-001, 4.41938179e-001, 1.66387960e-001,
       4.17827298e-003, 9.44969427e-003, 4.18060201e-003, 1.94444444e-003,
       1.66666667e-003, 3.61111111e-003, 1.00194823e-001, 1.11420613e-001,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

In [16]:
model = Sequential()
nCol= 102
model.add(Dense(128, input_dim= nCol, activation = 'relu', name ='input'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(512, activation = 'relu'))
model.add(Dense(512, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid', name='output'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (Dense)               (None, 128)               13184     
                                                                 
 dense (Dense)               (None, 256)               33024     
                                                                 
 dense_1 (Dense)             (None, 512)               131584    
                                                                 
 dense_2 (Dense)             (None, 512)               262656    
                                                                 
 dense_3 (Dense)             (None, 128)               65664     
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 dense_5 (Dense)             (None, 32)                2

In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
istory = model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
746/746 [==============================] - 14s 16ms/step - loss: 0.4461 - accuracy: 0.8371
Epoch 2/100
746/746 [==============================] - 11s 15ms/step - loss: 0.4407 - accuracy: 0.8371
Epoch 3/100
746/746 [==============================] - 10s 14ms/step - loss: 0.4381 - accuracy: 0.8371
Epoch 4/100
746/746 [==============================] - 12s 16ms/step - loss: 0.4358 - accuracy: 0.8371
Epoch 5/100
746/746 [==============================] - 12s 17ms/step - loss: 0.4342 - accuracy: 0.8371
Epoch 6/100
746/746 [==============================] - 15s 20ms/step - loss: 0.4314 - accuracy: 0.8372
Epoch 7/100
746/746 [==============================] - 11s 15ms/step - loss: 0.4285 - accuracy: 0.8377
Epoch 8/100
746/746 [==============================] - 10s 14ms/step - loss: 0.4262 - accuracy: 0.8380
Epoch 9/100
746/746 [==============================] - 11s 14ms/step - loss: 0.4230 - accuracy: 0.8396
Epoch 10/100
746/746 [==============================] - 11s 14ms/step - l

In [20]:
_, accuracy = model.evaluate(X_test, y_test)
print('accuracy : ', accuracy * 100)

497/497 [==============================] - 2s 4ms/step - loss: 0.6490 - accuracy: 0.8614
accuracy :  86.13836765289307


In [21]:
y_pred = model.predict(X_test)

497/497 [==============================] - 2s 4ms/step


In [ ]:
# for i in range(y_pred.shape[0]):
#     print(y_pred[i], '  , ', y_test[i])

In [26]:
ac = 0
fl = 0

d_ac = 0
d_fl = 0
for i in range(y_pred.shape[0]):
    if y_pred[i] > 0.8:
        if(y_test[i] == 1.0):
            ac += 1
        else:
            fl += 1
            
    if y_pred[i] < 0.65:
        if(y_test[i] == 0.0):
            d_ac += 1
        else:
            d_fl += 1
    #print(i, '  pred : ' , y_pred[i], ' test : ' , y_test[i])

print('============ 0 =============')
print('d_sum : ', d_ac+ d_fl)
print('d_  ', d_ac, ' and ', d_fl)
print('d_ratio : ', d_ac / (d_ac+d_fl), end='\n\n')
    
print('============ 1 =============')
print('sum : ', ac+ fl)
print(ac, ' and ', fl)
print('ratio : ', ac / (ac+fl))

============ 0 =============
d_sum :  13901
d_   12510  and  1391
d_ratio :  0.8999352564563701

============ 1 =============
sum :  1686
1158  and  528
ratio :  0.6868327402135231


In [27]:
model_name = 'fProfit15'
save_model_name = model_name +'.h5'
output_onnx_file_name = model_name + '.onnx'

In [28]:
model.save(save_model_name)

In [29]:
import tensorflow as tf
# h5 to pb
model_convert = tf.keras.models.load_model(save_model_name, compile=False)
model_convert.save('./model', save_format="tf")

# pb to onnx 
import os
os.system('python -m tf2onnx.convert --saved-model ./model/ --output ' + output_onnx_file_name + ' --opset 13')

INFO:tensorflow:Assets written to: ./model\assets


0

In [31]:
def WriteScaleData(table, feature_names, scale_method, model_name, pandas_data ):
    try:
        today = datetime.datetime.today()
        scaleMethod = scale_method
        sModel = model_name
        fD0 = None
        fD1 = None
        fD2 = None

        for idx, col in enumerate(feature_names):
            sVar = col
            if scale_method == 'MinMax': # MinMax Scaler
                fD0 = pandas_data[col].min()
                fD1 = pandas_data[col].max()
                fD2 = fD0
            elif scale_method == 'Standard': # Standard Scaler
                fD0 = pandas_data[col].mean()
                fD1 = pandas_data[col].std()
                fD2 = 0
            elif scale_method == 'Robust' : # Robust Scaler
                fD0 = pandas_data[col].median()
                fD1 = pandas_data[col].quantile(q= 0.75)
                fD2 = pandas_data[col].quantile(q= 0.25)
            else :
                raise Exception('Threr is no suitable scaler method')

            query = db.insert(table).values( {'dTime': today, 'sScaleMethod':scaleMethod, 'sVariableName':sVar, 
                            'sModelName':sModel, 'fD0':fD0, 'fD1':fD1, 'fD2':fD2, 'nSeq':idx})
            result_proxy = conn.execute(query)
            result_proxy.close()
        print('put scale to ', sModel, ' ends')
    except Exception as ex:
        print(ex)
        return;


WriteScaleData(table=table, feature_names=feature_names, scale_method=scale_method,
 model_name=output_onnx_file_name, pandas_data=br)

put scale to  fProfit15.onnx  ends
