# 데이터 획득 및 설정

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import graphviz
import os
from sklearn import tree, ensemble
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import shap
from sklearn.feature_selection import chi2, SelectKBest, f_classif, mutual_info_classif, f_regression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin/' # windows에서 graphviz를 사용하기 위해 변수경로 설정 

In [2]:
engine = create_engine('mysql://sbe03253:jin94099@database-2.clmg3ftdxi2a.ap-northeast-2.rds.amazonaws.com/MJTradierDB')
conn = engine.connect()

In [3]:
br = pd.read_sql_table('buyReports', conn)

# Filtering

In [4]:
br = br[( br['isAllBuyed'] == 1) & ( br['isAllSelled'] == 1) & (br['nBuyVolume'] > 0)]

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer

X = br[
    [   'nBuyStrategyIdx',
        'nRqTime' , 
        'fStartGap' ,
        'fPowerWithOutGap' , 
        'fPower' , 
        'fPlusCnt07' , 
        'fMinusCnt07' , 
        'fPlusCnt09' , 
        'fMinusCnt09' ,
        'fPowerJar' , 
        'fOnlyDownPowerJar' , 
        'fOnlyUpPowerJar' , 
        'nTradeCnt' , 
        'nChegyulCnt' , 
        'nHogaCnt' , 
        'nNoMoveCnt' , 
        'nFewSpeedCnt' ,
        'nMissCnt' , 
        'lTotalTradeVolume' , 
        'lTotalBuyVolume' , 
        'lTotalSellVolume' ,
        'nAccumUpDownCount' ,
        'fAccumUpPower' , 
        'fAccumDownPower' ,
        'lTotalTradePrice' , 
        'lTotalBuyPrice' , 
        'lTotalSellPrice' , 
        'lMarketCap' , 
        'nAccumCountRanking' , 
        'nMarketCapRanking' , 
        'nPowerRanking' , 
        'nTotalBuyPriceRanking' , 
        'nTotalBuyVolumeRanking' ,
        'nTotalTradePriceRanking' ,
        'nTotalTradeVolumeRanking' ,
        'nTotalRank' , 
        'nMinuteTotalRank' , 
        'nMinuteTradePriceRanking' ,
        'nMinuteTradeVolumeRanking' , 
        'nMinuteBuyPriceRanking' , 
        'nMinuteBuyVolumeRanking' ,
        'nMinutePowerRanking' , 
        'nMinuteCountRanking' ,
        'nMinuteUpDownRanking' ,
        'nFakeBuyCnt' , 
        'nFakeAssistantCnt' ,
        'nFakeResistCnt' , 
        'nPriceUpCnt' , 
        'nPriceDownCnt' ,
        'nTotalFakeCnt' ,
        'nTotalFakeMinuteCnt' ,
        'nUpCandleCnt' , 
        'nDownCandleCnt' ,
        'nUpTailCnt' , 
        'nDownTailCnt' ,
        'nShootingCnt' ,
        'nCandleTwoOverRealCnt' ,
        'nCandleTwoOverRealNoLeafCnt' , 
        'fSpeedCur' , 
        'fHogaSpeedCur' ,
        'fTradeCur' , #
        'fPureTradeCur' , #
        'fPureBuyCur' , #
        'fHogaRatioCur' ,  
        'fSharePerHoga' , 
        'fSharePerTrade' ,
        'fHogaPerTrade' , 
        'fTradePerPure' , 
        'fMaDownFsVal' , 
        'fMa20mVal' , 
        'fMa1hVal' ,
        'fMa2hVal' ,
        'fMaxMaDownFsVal' ,
        'fMaxMa20mVal' ,
        'fMaxMa1hVal' ,
        'fMaxMa2hVal' ,
        'nMaxMaDownFsTime' ,
        'nMaxMa20mTime' ,
        'nMaxMa1hTime' ,
        'nMaxMa2hTime' ,
        'nDownCntMa20m' ,
        'nDownCntMa1h' ,
        'nDownCntMa2h' ,
        'nUpCntMa20m' ,
        'nUpCntMa1h' ,
        'nUpCntMa2h' ,
        'fMSlope' ,
        'fISlope' ,
        'fTSlope' ,
        'fHSlope' ,
        'fRSlope' ,
        'fDSlope' ,
        'fMAngle' ,
        'fIAngle' ,
        'fTAngle' ,
        'fHAngle' ,
        'fRAngle' ,
        'fDAngle' ,
        'nCrushCnt' ,
        'nCrushUpCnt' ,
        'nCrushDownCnt' ,
        'nCrushSpecialDownCnt' ]
]
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

# transformer = Normalizer().fit(X)  
# X = transformer.transform(X)

print(type(X))
print(X)
#X = X.to_numpy()

<class 'numpy.ndarray'>
[[0.20338983 0.22074577 0.49956934 ... 0.         0.         0.        ]
 [0.10169492 0.97527707 0.4861169  ... 0.         0.         0.        ]
 [0.11016949 0.97694503 0.4861169  ... 0.         0.         0.        ]
 ...
 [0.15254237 0.74500537 0.49956934 ... 0.         0.         0.        ]
 [0.19491525 0.0631417  0.49956934 ... 0.         0.         0.        ]
 [0.13559322 0.62083472 0.50483703 ... 0.         0.         0.        ]]


In [ ]:
# y_continuos = br[ ['fProfit'] ]
# y_categorical = (br['fProfit'].apply(lambda x: 1 if x >= 0.01 else 0)).to_frame() # categorical
# y_categorical = b
type(X)

In [6]:
crit = 0.015
br.loc[br['fProfit'] >= crit, 'isProfit'] = 1
br.loc[br['fProfit'] < crit, 'isProfit'] = 0
# y = pd.get_dummies( br['isProfit'] )
y = br['isProfit']
y = y.to_numpy()

# y = br['fProfit'] * 100
# y

In [24]:
br.loc[br['fMaxPowerAfterBuyWhile10'] >= 0.035, 'isGood'] = 1
br.loc[br['fMaxPowerAfterBuyWhile10'] < 0.035, 'isGood'] = 0
# y = pd.get_dummies( br['isGood'] )
y = br['isGood']
y = y.to_numpy()

In [9]:
br['isProfit'].unique()

array([0., 1.])

In [25]:
br['isGood'].unique()

array([0., 1.])

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=16)

In [27]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
y_train

(42239, 102)
(42239,)
(14080, 102)
(14080,)


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
X[1]

In [28]:
model = Sequential()
nCol= 102
model.add(Dense(1024, input_dim= nCol, activation = 'relu'))
model.add(Dense(1024, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 1024)              105472    
                                                                 
 dense_7 (Dense)             (None, 1024)              1049600   
                                                                 
 dense_8 (Dense)             (None, 256)               262400    
                                                                 
 dense_9 (Dense)             (None, 128)               32896     
                                                                 
 dense_10 (Dense)            (None, 64)                8256      
                                                                 
 dense_11 (Dense)            (None, 1)                 65        
                                                                 
Total params: 1,458,689
Trainable params: 1,458,689
No

In [ ]:
print(X_test.shape)
print(y_test.shape)

In [29]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
istory = model.fit(X_train, y_train, epochs=50, batch_size=50)

Epoch 1/50
845/845 [==============================] - 35s 39ms/step - loss: 0.4575 - accuracy: 0.7957
Epoch 2/50
845/845 [==============================] - 38s 45ms/step - loss: 0.4425 - accuracy: 0.7991
Epoch 3/50
845/845 [==============================] - 38s 45ms/step - loss: 0.4384 - accuracy: 0.8009
Epoch 4/50
845/845 [==============================] - 32s 37ms/step - loss: 0.4341 - accuracy: 0.8020
Epoch 5/50
845/845 [==============================] - 35s 42ms/step - loss: 0.4316 - accuracy: 0.8031
Epoch 6/50
845/845 [==============================] - 29s 34ms/step - loss: 0.4291 - accuracy: 0.8055
Epoch 7/50
845/845 [==============================] - 31s 36ms/step - loss: 0.4246 - accuracy: 0.8069
Epoch 8/50
845/845 [==============================] - 37s 44ms/step - loss: 0.4212 - accuracy: 0.8109
Epoch 9/50
845/845 [==============================] - 32s 38ms/step - loss: 0.4173 - accuracy: 0.8138
Epoch 10/50
845/845 [==============================] - 53s 63ms/step - loss: 0.413

In [30]:
_, accuracy = model.evaluate(X_test, y_test)
print('accuracy : ', accuracy * 100)

440/440 [==============================] - 4s 9ms/step - loss: 0.4314 - accuracy: 0.8937
accuracy :  89.36789631843567


In [31]:
y_pred = model.predict(X_test)

440/440 [==============================] - 4s 9ms/step


In [ ]:
X_test

In [ ]:
y_pred[0]

In [ ]:
for i in range(y_pred.shape[0]):
    print(y_pred[i], '  , ', y_test[i])

In [35]:
ac = 0
fl = 0

d_ac = 0
d_fl = 0
for i in range(y_pred.shape[0]):
    if y_pred[i] > 0.8:
        if(y_test[i] == 1.0):
            ac += 1
        else:
            fl += 1
            
    if y_pred[i] < 0.65:
        if(y_test[i] == 0.0):
            d_ac += 1
        else:
            d_fl += 1
    #print(i, '  pred : ' , y_pred[i], ' test : ' , y_test[i])


print('d_sum : ', d_ac+ d_fl)
print('d_  ', d_ac, ' and ', d_fl)
print('d_ratio : ', d_ac / (d_ac+d_fl))
    
print('sum : ', ac+ fl)
print(ac, ' and ', fl)
print('ratio : ', ac / (ac+fl))

d_sum :  11914
d_   10839  and  1075
d_ratio :  0.9097700184656706
sum :  1841
1592  and  249
ratio :  0.8647474198804997


In [12]:
save_model_name = 'fProfit15_test.h5'
output_onnx_file_name = 'model_output.onnx'

In [ ]:
model.save(save_model_name)

In [14]:
import tensorflow as tf
# h5 to pb
model_convert = tf.keras.models.load_model(save_model_name, compile=False)
model_convert.save('./model', save_format="tf")

# pb to onnx 
import os
os.system('python -m tf2onnx.convert --saved-model ./model/ --output ' + output_onnx_file_name + ' --opset 13')

INFO:tensorflow:Assets written to: ./model\assets


0